/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#003c90",
        "primary-container": "#0f52ba",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b0c6ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#bcceff",
        "on-primary-fixed": "#001945",
        "on-primary-fixed-variant": "#00419c",
        "inverse-primary": "#b0c6ff",

        "secondary": "#006a61",
        "secondary-container": "#86f2e4",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",

        "tertiary": "#394246",
        "tertiary-container": "#50595e",
        "tertiary-fixed": "#dbe4ea",
        "tertiary-fixed-dim": "#bfc8ce",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c6cfd5",
        "on-tertiary-fixed": "#141d21",
        "on-tertiary-fixed-variant": "#3f484d",

        "surface": "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "surface-variant": "#d5e3fc",
        "surface-tint": "#1d59c1",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#434653",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",

        "background": "#f8f9ff",
        "on-background": "#0d1c2e",

        "outline": "#737784",
        "outline-variant": "#c3c6d5",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        "card": "0px 16px 16px 0px rgba(15, 82, 186, 0.04)",
        "card-hover": "0px 16px 32px -8px rgba(15, 82, 186, 0.08)",
        "app-bar": "0px 16px 16px 0px rgba(15, 82, 186, 0.04)",
        "bottom-nav": "0px -4px 16px 0px rgba(15, 82, 186, 0.04)",
        "btn": "0px 4px 12px 0px rgba(15, 82, 186, 0.12)",
      },
    },
  },
  plugins: [],
}
